name: lvs2_
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - torchvision
  - pip:
      - accelerate
      - av
      - decord
      - diffusers[torch]==0.21.0
      - einops
      - ffmpeg
      - imageio
      - imageio-ffmpeg
      - pandas
      - timm
      - tqdm
      - transformers
      - omegaconf
      - rotary_embedding_torch
      - ftfy
      - beautifulsoup4
      - bs4