ckpt: ./ckpt/checkpoint.pt
long_text_encoder_path: ./ckpt/longclip-L.pt
save_img_path: "./sample_videos/"
pretrained_model_path: "./ckpt/stable-diffusion-v1-4"
pretrained_svd_model_path: "./ckpt/stable-diffusion-v1-4"

# model config: 
model: UNet
video_length: 64
# image_size: [576, 1024]
image_size: [320, 512]
# beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"
rescale_betas_zero_snr: False

# beta_start: 0.0001
# beta_end: 0.02
# beta_schedule: "scaled_linear"
# rescale_betas_zero_snr: False
# 
# beta_start: 0.00085
# beta_end: 0.012
# beta_schedule: "scaled_linear"
# rescale_betas_zero_snr: False
# 
# beta_start: 0.00085
# beta_end: 0.012
# beta_schedule: "linear"
# rescale_betas_zero_snr: False

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: 17
run_time: 0
lora_rank: 4
guidance_scale: 7.0
sample_method: 'DDIM'
num_sampling_steps: 50

shot_mask: # False
  - [False, False, False, False]
  - [False]
  - [False, False, True, True] 
